### ISSUE TITLE
Generate short RNA count matrices for 3 species 

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive-expression#15]

**Comment by shedurkin** [comment]
We now have sRNA, miRNA, and siRNA count matrices, summarized from ShortStack 4.1.0 outputs. This includes both raw counts, normalized counts, and variance stabilized counts for all three sets in all three species.  

output folders where these count matrices are stored:
[Apul](https://github.com/urol-e5/deep-dive-expression/tree/main/D-Apul/output/03.1-Apul-sRNA-summary)
[Peve](https://github.com/urol-e5/deep-dive-expression/tree/main/E-Peve/output/03.1-Peve-sRNA-summary)
Ptuh

direct links to some of the important ones:
[Apul miRNA raw count matrix](https://github.com/urol-e5/deep-dive-expression/blob/main/D-Apul/output/03.1-Apul-sRNA-summary/Apul_miRNA_ShortStack_counts_formatted.txt)
[Apul siRNA raw count matrix](https://github.com/urol-e5/deep-dive-expression/blob/main/D-Apul/output/03.1-Apul-sRNA-summary/Apul_siRNA_ShortStack_counts_formatted.txt)
[Peve miRNA raw count matrix](https://github.com/urol-e5/deep-dive-expression/blob/main/E-Peve/output/03.1-Peve-sRNA-summary/Peve_miRNA_ShortStack_counts_formatted.txt)
[Peve siRNA raw count matrix](https://github.com/urol-e5/deep-dive-expression/blob/main/E-Peve/output/03.1-Peve-sRNA-summary/Peve_siRNA_ShortStack_counts_formatted.txt)
[Ptuh miRNA raw count matrix](https://github.com/urol-e5/deep-dive-expression/blob/main/F-Ptuh/output/03.1-Ptuh-sRNA-summary/Ptuh_miRNA_ShortStack_counts_formatted.txt)
[Ptuh siRNA raw count matrix](https://github.com/urol-e5/deep-dive-expression/blob/main/F-Ptuh/output/03.1-Ptuh-sRNA-summary/Ptuh_siRNA_ShortStack_counts_formatted.txt)

**Comment by sr320** [comment]
added to wiki at https://github.com/urol-e5/deep-dive-expression/wiki/03%E2%80%90Expression-Count-Matrices
