### ISSUE TITLE
Rerun miRNA discovery with new pulcra genome

### ISSUE THREAD

**Issue by sr320** [urol-e5/deep-dive-expression#3]

**Comment by shedurkin** [comment]
Reran ShortStack miRNA discovery on _all three_ species, using the updated version of Shortstack (4.1.0). This version is much faster and provides structrural visualizations of annotated miRNAs. There were some small differences in outputs between the two versions, even when using the same inputs, so we shuold make sure we use the 4.1.0 output for all species.

[Apul, new genome, ShortStack 4.1.0](https://github.com/urol-e5/deep-dive-expression/blob/main/D-Apul/code/11-Apul-sRNA-ShortStack_4.1.0-pulchra_genome.md)
[Peve, ShortStack 4.1.0](https://github.com/urol-e5/deep-dive-expression/blob/main/E-Peve/code/05-Peve-sRNA-ShortStack_4.1.0.md)
Ptuh, ShortStack 4.1.0
